# -*- coding: utf-8 -*-
"""LLM (Text_SQL).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M-R_K_j9ry6h3nglaGNJfUj8JqW1tjmM
"""

!pip install -U langchain-google-genai

try:
    from google.colab import userdata
    api_key = userdata.get('GEMINI_API_KEY')

    if not api_key:
        raise ValueError(" GEMINI_API_KEY not found in Colab userdata. Please set it before running.")
except Exception as e:
    print(f"Error while retrieving API key: {e}")
    api_key = No

try:
    from langchain_google_genai import ChatGoogleGenerativeAI
    from IPython.display import display, Markdown
    import textwrap
except ImportError as e:
    raise ImportError("Required libraries not found. Please reinstall using !pip install -U langchain-google-genai") from e

try:
    if api_key:
        llm = ChatGoogleGenerativeAI(
            model="gemini-2.5-flash",
            temperature=0.2,
            google_api_key=api_key
        )
    else:
        llm = None
        print(" Model not initialized due to missing API key.")
except Exception as e:
    print(f"Error initializing the LLM: {e}")
    llm = No

def to_markdown(text):
    try:
        text = text.replace('•', '  *')
        return Markdown(textwrap.indent(text, '> ', predicate=lambda _: True))
    except Exception as e:
        print(f"Error in to_markdown: {e}")
        return Markdown(">  Unable to render markdown properly.")

llm = ChatGoogleGenerativeAI(
    model="gemini-2.5-flash",
   temperature=0.2,
    google_api_key=api_key
)

db_schema = """
You are an expert SQL query generator and database analyst.
The database schema is as follows:

TABLE: Customers(id, name, email, city)
TABLE: Orders(id, customer_id, product, amount, order_date)

Instructions:
* Always generate **syntactically correct**, **optimized**, and **executable** SQL queries.
* Use **JOINs**, **GROUP BY**, **aggregations**, and **subqueries** when necessary.
* Consider relationships between tables (e.g., Orders.customer_id = Customers.id).
* If the question involves totals, averages, or counts — use appropriate **aggregate functions**.
* Use **clear aliases** for readability (e.g., c for Customers, o for Orders).
* Never include explanations or comments in the final SQL output — only the query itself.
* Prefer ANSI SQL syntax to ensure compatibility across databases.

Now generate the correct and optimized SQL query for the given question.
"""

def text_to_sql_markdown(user_question):
    if not llm:
        print(" LLM model not initialized. Please check your API key or initialization.")
        return

    try:
        prompt = f"{db_schema}\n\nQuestion: {user_question}\n\nSQL Query:"
        response = llm.invoke(prompt)

        if not hasattr(response, "content") or not response.content.strip():
            raise ValueError("Empty response received from model.")

        sql_query = response.content.strip()

        display(to_markdown(f"**Question:** {user_question}\n\n**SQL Query:**\n```sql\n{sql_query}\n```"))

    except Exception as e:
        print(f" Error generating SQL for '{user_question}': {e}")
        display(Markdown(f">  Could not generate SQL for this question: **{user_question}**"))

text_to_sql_markdown("List all customers from New York")
text_to_sql_markdown("Show total order amount for each customer")
text_to_sql_markdown("Find customers who have placed more than 3 orders")

