# -*- coding: utf-8 -*-
"""Genai-Kata-6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x6ItaHKV5V2LuuJEu3G3B5872dUpYPs2

# Problem Statement

**Building a Movie Recommendation System with Chroma Vector DB**

**Scenario:** Develop a Python script that utilizes Chroma Vector DB to create a movie recommendation system based on user preferences via query and movie descriptions.

**Tasks:**

1. For each movie, extract the description text.
2. Use any embedding_model to generate an embedding for the description.
3. Insert the movie description, its embedding, and the metadata (genre and director) into the ChromaDB collection
4. Based on the user query form a proper filter expression.
5. Retrieve the top 5 results based on the user query.

**Dataset:**

[**Movies Dataset**](https://docs.google.com/spreadsheets/d/17zn3h5pDWTz1CEiouAc0c5KWpobk7OFg8D0wmO6QJoE/edit?usp=sharing)

# Step 1: Install Dependencies
"""

!pip install -q chromadb langchain sentence-transformers pandas

"""# Step 2: Mount Google Drive"""

from google.colab import drive
import pandas as pd

# Mount Google Drive
try:
    drive.mount('/content/drive')
    print(" Google Drive mounted successfully.")
except Exception as e:
    print(" Error mounting Drive:", e)

"""# Step 3: Load Datasets"""

# Load dataset
try:
    file_path = "/content/drive/MyDrive/Kata-6/Movies-Dataset.csv"
    df = pd.read_csv(file_path)
    print(" Dataset loaded successfully!\n")

    # Normalize column names (important for later filtering)
    df.columns = df.columns.str.strip().str.lower()

    # Show first 5 rows in table form
    from IPython.display import display
    display(df.head())

except FileNotFoundError:
    print(" File not found. Please check your path.")
except pd.errors.EmptyDataError:
    print(" The file is empty.")
except Exception as e:
    print("Error loading dataset:", e)

"""# Step 4: Prepare Documents for Embedding"""

from langchain_core.documents import Document

data = []

try:
    for _, row in df.iterrows():
        title = row.get("title", "")
        description = row.get("description", "No description available")
        genre = row.get("genre", "")
        director = row.get("director", "")

        metadata = {"title": title, "genre": genre, "director": director}
        doc = Document(page_content=str(description), metadata=metadata)
        data.append(doc)

    print(f"Successfully created {len(data)} documents for ChromaDB.")
except Exception as e:
    print(" Error preparing documents:", e)

"""# Step 5: Generate Embeddings for Each Description"""

from sentence_transformers import SentenceTransformer

try:
    embedding_model = SentenceTransformer('all-MiniLM-L6-v2')
    print(" Embedding model loaded successfully.")
except Exception as e:
    print(" Error loading embedding model:", e)

"""# Now, generate the embeddings:"""

try:
    texts = [doc.page_content for doc in data]
    embeddings = embedding_model.encode(texts, show_progress_bar=True)
    print(f" Generated embeddings for {len(embeddings)} documents.")
except Exception as e:
    print(" Error generating embeddings:", e)

"""# Step 6: Store Data in Chroma Vector Database"""

import chromadb

try:
    client = chromadb.Client()
    collection = client.get_or_create_collection("movie_recommendations")
    print(" ChromaDB collection created or loaded successfully.")
except Exception as e:
    print(" Error creating ChromaDB collection:", e)

"""# Now insert the movie data and embeddings into the collection:"""

try:
    collection.add(
        ids=[f"id_{i}" for i in range(len(data))],
        embeddings=embeddings.tolist(),
        documents=[doc.page_content for doc in data],
        metadatas=[doc.metadata for doc in data]
    )
    print(" All movie data inserted into ChromaDB collection successfully.")
except Exception as e:
    print(" Error inserting data into ChromaDB:", e)

"""# Step 7: Query the ChromaDB for Recommendations"""

user_query = input(" Enter your movie preference query: ")

try:
    # Ask if user wants to filter by genre or director
    filter_choice = input("Would you like to filter by 'genre' or 'director'? (leave blank to skip): ").strip().lower()
    filter_value = ""

    if filter_choice in ["genre", "director"]:
        filter_value = input(f"Enter the {filter_choice} you want to search for: ").strip()

    # Prepare query embedding
    query_embedding = embedding_model.encode([user_query])

    # Query ChromaDB
    results = collection.query(
        query_embeddings=query_embedding.tolist(),
        n_results=5
    )

    print("\n Top 5 Recommended Movies:\n")

    count = 0
    for i in range(len(results['documents'][0])):
        meta = results['metadatas'][0][i]
        title = meta['title']
        genre = meta['genre']
        director = meta['director']

        # Apply genre/director filter if provided
        if filter_value:
            if filter_choice == "genre" and filter_value.lower() not in genre.lower():
                continue
            if filter_choice == "director" and filter_value.lower() not in director.lower():
                continue

        count += 1
        print(f" Title: {title}")
        print(f" Genre: {genre}")
        print(f" Director: {director}")
        print(f" Description: {results['documents'][0][i][:200]}...\n")

    if count == 0:
        print(" No matching movies found for your filter.")

except Exception as e:
    print(" Error during query or retrieval:", e)