# -*- coding: utf-8 -*-
"""Python_Tasks 1 & 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TA4kHK-CULZIUpp_h0EEXr_dSUEuHG7_

# Problem 1
"""

def single_number(nums):
    result = 0
    for n in nums:
        result ^= n
    return result

print(single_number([4, 1, 2, 1, 2]))

"""# Problem 2"""

class BankAccount:
    def __init__(self, initial_balance=0):
        self.__balance = initial_balance

    def deposit(self, amount):
        if amount > 0:
            self.__balance += amount
            print(f"Deposited: {amount}")
        else:
            print("Deposit amount must be positive!")

    def withdraw(self, amount):
        if 0 < amount <= self.__balance:
            self.__balance -= amount
            print(f"Withdrawn: {amount}")
        else:
            print("Insufficient funds or invalid amount!")

    def get_balance(self):
           return self.__balance


acc = BankAccount(1000)   # Initial balance = 1000
acc.deposit(500)                 # Add 500 → total = 1500
acc.withdraw(300)              # Subtract 300 → total = 1200
print(acc.get_balance())     # Output: 1200

# Direct access should fail
print(acc.__balance)      # Raises AttributeError